'use client';

import { useState, useEffect, useCallback } from 'react';
import Image from 'next/image';
import Link from 'next/link';
import { createClient } from '@/lib/client';
import AdmissionLetter from '@/components/AdmissionLetter';
import GuardianManager from '@/components/GuardianManager';
import { getCourseTypeConfig } from '@/lib/course-structure';

export default function ApplyPage() {
  const [supabase, setSupabase] = useState<any>(null);
  const [kcseGrades, setKcseGrades] = useState<{grade: string; value: number}[]>([]);
  const getGradeValue = useCallback((grade: string) => {
    const g = kcseGrades.find(k => k.grade === grade);
    return g?.value ?? 0;
  }, [kcseGrades]);
  const currentYear = new Date().getFullYear();
  const [formData, setFormData] = useState({
    firstName: '',
    middleName: '',
    lastName: '',
    gender: '',
    phone: '',
    email: '',

    kcseGrade: '',
    examBody: '',
    intake: '',
    academic_calendar_id: '',
    course: '',
    courseType: '',
    campus: '',
    enrollmentType: 'new',
    applicationDate: ''
  });
  const [courses, setCourses] = useState<any[]>([]);
  const [availableCourseTypes, setAvailableCourseTypes] = useState<string[]>([]);
  const [suggestedCourses, setSuggestedCourses] = useState<any[]>([]);
  const [availableIntakes, setAvailableIntakes] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [submitting, setSubmitting] = useState(false);
  const [currentStep, setCurrentStep] = useState<'application' | 'guardian' | 'confirmation'>('application');
  const [savedApplicationId, setSavedApplicationId] = useState<string | null>(null);
  const [submittedData, setSubmittedData] = useState<any>(null);

  // Initialize Supabase client only on client side
  useEffect(() => {
    try {
      const client = createClient();
      console.log('Supabase client created:', client ? 'success' : 'failed');
      setSupabase(client);
      // Load KCSE grades from DB
      client.from('kcse_grades').select('grade, value').order('sort_order').then((res: any) => {
        if (res.data) setKcseGrades(res.data);
      });
    } catch (err: any) {
      console.error('Error creating Supabase client:', err);
      alert('Failed to initialize: ' + err.message);
    }
  }, []);

  // Admission number auto-generated by DB trigger on insert

  // Load courses from Supabase
  useEffect(() => {
    console.log('Course load effect triggered, supabase:', supabase ? 'exists' : 'null');
    if (!supabase) {
      console.log('Supabase not ready yet, skipping course load');
      return;
    }

    const loadCourses = async () => {
      try {
        console.log('Starting to load courses...');
        const { data, error } = await supabase
          .from('courses')
          .select(`
            *,
            course_types (
              id,
              level,
              enabled,
              study_mode,
              duration_months,
              modules (
                module_index,
                exam_body,
                semesters (
                  semester_index,
                  duration_months,
                  fee,
                  practical_fee,
                  internal_exams
                )
              )
            )
          `)
          .order('name');

        if (error) {
          console.error('Error loading courses:', error);
          alert('Error loading courses: ' + error.message + '\nCode: ' + error.code);
        } else {
          console.log('Courses loaded successfully:', data?.length || 0, 'courses');
          if (data && data.length > 0) {
            console.log('First course:', data[0]);
            console.log('First course types:', data[0]?.course_types);
            if (data[0]) {
              console.log('First course min_kcse_grade:', data[0].min_kcse_grade);
            }
            setCourses(data);
          } else {
            console.log('No courses found in database');
            setCourses([]);
          }
        }
      } catch (err: any) {
        console.error('Exception loading courses:', err);
        alert('Exception: ' + err.message);
      } finally {
        setLoading(false);
      }
    };

    loadCourses();

    // Load available intakes from backend
    const loadIntakes = async () => {
      const { data: cal } = await supabase
        .from('academic_calendar')
        .select('id, term_name, term_start_date, intake_start_date, intake_end_date, campus')
        .gte('intake_end_date', new Date().toISOString().split('T')[0])
        .order('term_start_date');
      if (cal) {
        // Deduplicate by month/year (same intake for both campuses)
        const seen = new Set<string>();
        const unique = cal.filter((c: any) => {
          const key = c.term_start_date ? c.term_start_date.substring(0, 7) : c.id;
          if (seen.has(key)) return false;
          seen.add(key);
          return true;
        });
        setAvailableIntakes(unique);
      }
    };
    loadIntakes();
  }, [supabase]);

  // Check if student should be assigned to bridge stream
  const checkBridgeEligibility = async (intake: string, campus: string) => {
    if (!supabase) return false;

    try {
      const intakeParts = intake.split(' ');
      const intakeMonthYear = intakeParts.slice(-2).join(' ');

      const { data: calendarData } = await supabase
        .from('academic_calendar')
        .select('*')
        .eq('campus', campus)
        .order('intake_start_date', { ascending: false })
        .limit(1);

      if (!calendarData || calendarData.length === 0) return false;

      const calendar = calendarData[0];
      const currentDate = new Date();
      const intakeStartDate = new Date(calendar.intake_start_date);
      const bridgeTriggerDay = calendar.bridge_trigger_day || 30;
      const intakeEndDate = new Date(calendar.intake_end_date);

      const daysSinceIntake = Math.floor((currentDate.getTime() - intakeStartDate.getTime()) / (1000 * 60 * 60 * 24));

      // Days 0-30: Regular student
      // Days 30-45: Bridge student (late joiner)
      // After 45 (intake_end_date): Intake closed
      if (daysSinceIntake >= bridgeTriggerDay && currentDate <= intakeEndDate) {
        return 'bridge'; // Bridge stream
      }
      return false;
    } catch (err) {
      console.error('Error checking bridge eligibility:', err);
      return false;
    }
  };

  // Compare student grade with course minimum grade
  const compareGrades = (studentGrade: string, minRequiredGrade: string): boolean => {
    if (!studentGrade || !minRequiredGrade) return false;
    const studentValue = getGradeValue(studentGrade);
    const minValue = getGradeValue(minRequiredGrade);
    console.log(`Grade compare: ${studentGrade}(${studentValue}) >= ${minRequiredGrade}(${minValue}) = ${studentValue >= minValue}`);
    return studentValue >= minValue;
  };

  // Get exam body for a course from course ID prefix
  const getExamBodyFromCourseId = (courseId: string): string => {
    if (courseId.startsWith('KNEC-')) return 'KNEC';
    if (courseId.startsWith('CDACC-')) return 'CDACC';
    if (courseId.startsWith('JP-')) return 'JP';
    return 'internal';
  };

  // Format course type with exam body for display
  const formatCourseTypeLabel = (level: string, examBody: string): string => {
    const labels: Record<string, Record<string, string>> = {
      KNEC: {
        diploma: 'KNEC Diploma',
        certificate: 'KNEC Certificate',
        artisan: 'KNEC Artisan',
        craft: 'KNEC Craft',
      },
      CDACC: {
        level6: 'CDACC Level 6 (Higher Diploma)',
        level5: 'CDACC Level 5 (Diploma)',
        level4: 'CDACC Level 4 (Certificate)',
      },
      JP: {
        diploma: 'JP Diploma',
        certificate: 'JP Certificate',
      },
      internal: {
        diploma: 'Internal Diploma',
        certificate: 'Internal Certificate',
      },
    };
    return labels[examBody]?.[level] || `${examBody} ${level}`;
  };

  // Get available course types for a course based on student's grade and exam body
  const getAvailableCourseTypes = (course: any, studentGrade: string, examBody: string): string[] => {
    if (!course || !studentGrade || !examBody) return [];
    
    const availableTypes: string[] = [];
    const courseTypes = course.course_types || [];
    
    // Use course.exam_body column first, fallback to ID prefix
    const courseExamBody = course.exam_body || getExamBodyFromCourseId(course.id);
    
    // Convert array from relational database to object keyed by level
    const courseTypesObj: any = {};
    if (Array.isArray(courseTypes)) {
      courseTypes.forEach((ct: any) => {
        courseTypesObj[ct.level] = ct;
      });
    } else {
      Object.assign(courseTypesObj, courseTypes);
    }
    
    // min_kcse_grade lives on the course, not course_types
    const courseMinGrade = course.min_kcse_grade || '';
    
    Object.entries(courseTypesObj).forEach(([type, data]: [string, any]) => {
      const config = getCourseTypeConfig(courseTypesObj, type);
      // Use course-level min_kcse_grade since course_types doesn't have it
      const minGrade = config?.minKcseGrade || courseMinGrade;
      
      const modules = data.modules || [];
      const hasExamBody = modules.some((m: any) => m.exam_body === examBody);
      const matchesByPrefix = !hasExamBody && courseExamBody === examBody;
      const gradeMatch = compareGrades(studentGrade, minGrade);
      
      if (config?.enabled && gradeMatch && (hasExamBody || matchesByPrefix)) {
        availableTypes.push(type);
      }
    });
    
    return availableTypes;
  };

  // Find suggested courses based on student's grade and exam body
  const findSuggestedCourses = (studentGrade: string, examBody: string): any[] => {
    if (!studentGrade || !examBody || courses.length === 0) return [];
    
    return courses.filter(course => {
      const availableTypes = getAvailableCourseTypes(course, studentGrade, examBody);
      return availableTypes.length > 0;
    });
  };

  // Auto-select course type when course, grade, and exam body are selected
  useEffect(() => {
    if (formData.course && formData.kcseGrade && formData.examBody) {
      const selectedCourse = courses.find(c => c.id === formData.course || c.course_id === formData.course);
      if (selectedCourse) {
        const availableTypes = getAvailableCourseTypes(selectedCourse, formData.kcseGrade, formData.examBody);
        setAvailableCourseTypes(availableTypes);
        
        // Update intake to include course name
        const intakeMonth = formData.intake.split(' ').slice(0, -1).join(' ') || 'September';
        const intakeYear = formData.intake.split(' ').pop() || currentYear.toString();
        const updatedIntake = `${selectedCourse.name} ${intakeMonth} ${intakeYear}`;
        setFormData(prev => ({ ...prev, intake: updatedIntake }));
        
        // Auto-select the first available type
        if (availableTypes.length > 0) {
          setFormData(prev => ({ ...prev, courseType: availableTypes[0] }));
        } else {
          setFormData(prev => ({ ...prev, courseType: '' }));
          // Find suggested courses
          const suggestions = findSuggestedCourses(formData.kcseGrade, formData.examBody);
          setSuggestedCourses(suggestions.filter(c => c.id !== formData.course && c.course_id !== formData.course));
        }
      }
    }
  }, [formData.course, formData.kcseGrade, formData.examBody, courses]);

  // Update suggested courses when grade or exam body changes
  useEffect(() => {
    if (formData.kcseGrade && formData.examBody) {
      const suggestions = findSuggestedCourses(formData.kcseGrade, formData.examBody);
      setSuggestedCourses(suggestions);
    }
  }, [formData.kcseGrade, formData.examBody, courses]);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!supabase) {
      alert('System is not ready. Please refresh the page.');
      return;
    }

    setSubmitting(true);

    try {
      // Check if phone number already exists
      const { data: existingApplication, error: checkError } = await supabase
        .from('applications')
        .select('phone')
        .eq('phone', formData.phone)
        .single();

      if (existingApplication) {
        alert('An application with this phone number already exists. Please contact the college for any changes.');
        setSubmitting(false);
        return;
      }

      // Set current date on submission
      const currentDate = new Date().toISOString();
      const submissionData = {
        ...formData,
        applicationDate: currentDate,
        status: 'pending',
        current_semester: 1
      };

      // Get course and course_type_id from courses array
      const selectedCourse = courses.find(c => c.id === formData.course);
      
      // Get course_type_id directly from database (more reliable than nested join)
      let courseTypeId = null;
      try {
        const { data: ctData } = await supabase
          .from('course_types')
          .select('id')
          .eq('course_id', formData.course)
          .eq('level', formData.courseType)
          .maybeSingle();
        courseTypeId = ctData?.id || null;
      } catch (e) {
        console.warn('course_type query failed, trying nested data', e);
        const ctData = selectedCourse?.course_types?.find((ct: any) =>
          ct.level?.toLowerCase() === formData.courseType?.toLowerCase()
        );
        courseTypeId = ctData?.id || null;
      }

      if (!courseTypeId) {
        console.error("Link Failure: Could not resolve course_type_id for:", formData.courseType, "in", selectedCourse);
        alert('System Error: Unable to link your selected course level. Please refresh and try again.');
        setSubmitting(false);
        return;
      }

      // Check if student should be in bridge stream
      const isBridgeEligible = await checkBridgeEligibility(formData.intake, formData.campus);
      let bridgeGroupId = null;
      let streamType = 'main';
      let bridgeStartDate = null;
      let syncTargetDate = null;
      let accelerationFactor = 1.0;

      if (isBridgeEligible) {
        // Get or create bridge group
        const { data: calendarData } = await supabase
          .from('academic_calendar')
          .select('*')
          .eq('campus', formData.campus)
          .order('intake_start_date', { ascending: false })
          .limit(1);

        if (calendarData && calendarData.length > 0) {
          const calendar = calendarData[0];
          const bridgeGroupName = `${formData.intake} Bridge`;
          
          // Check if bridge group already exists
          const { data: existingBridgeGroup } = await supabase
            .from('bridge_groups')
            .select('*')
            .eq('group_name', bridgeGroupName)
            .eq('campus', formData.campus)
            .eq('status', 'active')
            .single();

          if (existingBridgeGroup) {
            bridgeGroupId = existingBridgeGroup.id;
            syncTargetDate = existingBridgeGroup.sync_target_date;
            accelerationFactor = existingBridgeGroup.acceleration_factor;
          } else {
            // Create new bridge group
            const intakeStartDate = new Date(calendar.intake_start_date);
            const intakeEndDate = new Date(calendar.intake_end_date);
            const bridgeStartDate = new Date();
            
            // Calculate sync target date (midpoint of intake)
            const daysToSync = Math.floor((intakeEndDate.getTime() - intakeStartDate.getTime()) / (1000 * 60 * 60 * 24)) / 2;
            syncTargetDate = new Date(bridgeStartDate.getTime() + (daysToSync * 24 * 60 * 60 * 1000));
            
            // Calculate acceleration factor based on time remaining
            const daysRemaining = Math.floor((intakeEndDate.getTime() - bridgeStartDate.getTime()) / (1000 * 60 * 60 * 24));
            accelerationFactor = daysRemaining > 0 ? (90 / daysRemaining) : 1.5;
            if (accelerationFactor < 1.0) accelerationFactor = 1.0;
            if (accelerationFactor > 2.0) accelerationFactor = 2.0;

            const { data: newBridgeGroup } = await supabase
              .from('bridge_groups')
              .insert([{
                group_name: bridgeGroupName,
                intake: formData.intake,
                academic_calendar_id: calendar.id,
                campus: formData.campus,
                start_date: bridgeStartDate.toISOString().split('T')[0],
                sync_target_date: syncTargetDate.toISOString().split('T')[0],
                acceleration_factor: accelerationFactor,
                milestone_module: 1,
                milestone_semester: 1,
                status: 'active'
              }])
              .select()
              .single();

            bridgeGroupId = newBridgeGroup?.id;
          }

          streamType = 'bridge';
          bridgeStartDate = new Date().toISOString().split('T')[0];
        }
      }

      // Submit application to Supabase
      const apiRes = await fetch('/api/apply', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          full_name: [formData.firstName, formData.middleName, formData.lastName].filter(Boolean).join(' ').trim(),
          first_name: formData.firstName,
          middle_name: formData.middleName || null,
          last_name: formData.lastName,
          phone: formData.phone,
          email: formData.email || null,
          kcse_grade: formData.kcseGrade,
          exam_body: formData.examBody,
          intake: formData.intake,
          course_id: formData.course,
          course_type_id: courseTypeId,
          campus: formData.campus,
          enrollment_type: formData.enrollmentType || 'new',
          // admission_number auto-generated by DB trigger
          application_date: currentDate,
          stream_type: streamType,
          bridge_group_id: bridgeGroupId,
          bridge_start_date: bridgeStartDate,
          sync_target_date: syncTargetDate,
          acceleration_factor: accelerationFactor,
          gender: formData.gender,
          current_semester: 1,
        }),
      });

      const apiData = await apiRes.json();
      if (!apiRes.ok || apiData.error) {
        console.error('Error submitting application:', apiData);
        alert('Error: ' + (apiData.error || 'Submission failed'));
        setSubmitting(false);
        return;
      }
      const data = apiData.data;

      // Student profile is created server-side in /api/apply

      const courseInfo = courses.find(c => c.id === formData.course);
      const enrichedData = {
        ...data,
        course_id: data.course_id,
        course: courseInfo?.name || formData.course,
        course_type: formData.courseType
      };
      setSubmittedData(enrichedData);
      setSavedApplicationId(data.id);
      setCurrentStep('confirmation');
    } catch (err) {
      console.error('Error submitting application:', err);
      alert('Error submitting application. Please try again.');
    } finally {
      setSubmitting(false);
    }
  };

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>) => {
    setFormData({
      ...formData,
      [e.target.name]: e.target.value
    });
  };

  return (
    <div className="min-h-screen w-full bg-[#f8faff]">
      <div className="relative z-10 w-full max-w-2xl mx-auto px-4 md:px-6 py-4 md:py-6">
         {/* Header */}
         {!submittedData && (
          <div className="text-center mb-4">
            <Link href="/" className="inline-block mb-3">
              <div className="relative w-20 h-20 md:w-24 md:h-24">
                <Image
                  src="/logo.webp"
                  alt="East Africa Vision Institute Logo"
                  fill
                  className="object-contain"
                  sizes="(max-width: 768px) 128px, 160px"
                  loading="eager"
                />
              </div>
            </Link>
            <h1 className="text-xl md:text-2xl font-bold text-gray-900 mb-1">Apply to EAVI College</h1>
            <p className="text-gray-500 text-sm md:text-base">Fill out the form below to start your application</p>
          </div>
        )}

        {/* Step 3: Confirmation Screen */}
        {currentStep === 'confirmation' && submittedData && (
          <div className="bg-white rounded-xl p-4 md:p-5 border border-gray-200 shadow-sm">
            <div className="text-center mb-4">
              <div className="inline-block mb-4">
                <div className="relative w-16 h-16">
                  <Image
                    src="/logo.webp"
                    alt="East Africa Vision Institute Logo"
                    fill
                    className="object-contain"
                    sizes="96px"
                    loading="eager"
                  />
                </div>
              </div>
              <h1 className="text-lg md:text-xl font-bold text-white mb-1">Application Submitted!</h1>
              <p className="text-gray-500 text-sm md:text-base">Your application has been successfully submitted.</p>
            </div>

            <div className="bg-white/5 rounded-lg p-4 mb-4">
              <h2 className="text-base font-semibold text-white mb-2">Your Details</h2>
              <div className="space-y-3 text-sm">
                <div className="flex justify-between">
                  <span className="text-purple-300">Name:</span>
                  <span className="text-white font-medium">{submittedData.full_name}</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-purple-300">Course:</span>
                  <span className="text-white font-medium">{submittedData.course}</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-purple-300">Campus:</span>
                  <span className="text-white font-medium">{submittedData.campus}</span>
                </div>
              </div>
            </div>

            <div className="space-y-4">
              <AdmissionLetter studentData={submittedData} />

              <Link
                href="/"
                className="block w-full py-2 bg-white/10 hover:bg-white/20 border border-white/30 text-white rounded-lg transition-colors duration-300 text-base font-semibold text-center"
              >
                Back to Home
              </Link>
            </div>
          </div>
        )}

        {/* Step 1: Application Form */}
        {currentStep === 'application' && (
          <div className="bg-white rounded-xl p-4 md:p-5 border border-gray-200 shadow-sm">
            <form onSubmit={handleSubmit} className="space-y-3">
            {/* Hidden Fields */}
            <input
              type="hidden"
              name="applicationDate"
              value={formData.applicationDate}
            />


            {/* First & Last Name */}
            <div className="grid grid-cols-2 gap-2">
              <div>
                <label htmlFor="firstName" className="block text-gray-700 font-medium mb-1 text-xs md:text-sm">
                  First Name *
                </label>
                <input
                  type="text"
                  id="firstName"
                  name="firstName"
                  value={formData.firstName}
                  onChange={handleChange}
                  required
                  className="w-full px-3 py-2 bg-white border border-gray-300 rounded-lg text-gray-900 focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-green-500 text-sm md:text-base"
                />
              </div>
              <div>
                <label htmlFor="lastName" className="block text-gray-700 font-medium mb-1 text-xs md:text-sm">
                  Last Name *
                </label>
                <input
                  type="text"
                  id="lastName"
                  name="lastName"
                  value={formData.lastName}
                  onChange={handleChange}
                  required
                  className="w-full px-3 py-2 bg-white border border-gray-300 rounded-lg text-gray-900 focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-green-500 text-sm md:text-base"
                />
              </div>
            </div>
            {/* Middle Name (optional) */}
            <div>
              <label htmlFor="middleName" className="block text-gray-700 font-medium mb-1 text-xs md:text-sm">
                Middle Name (optional)
              </label>
              <input
                type="text"
                id="middleName"
                name="middleName"
                value={formData.middleName}
                onChange={handleChange}
                className="w-full px-3 py-2 bg-white border border-gray-300 rounded-lg text-gray-900 focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-green-500 text-sm md:text-base"
              />
            </div>

            {/* Gender */}
            <div>
              <label htmlFor="gender" className="block text-gray-700 font-medium mb-1 text-xs md:text-sm">
                Gender *
              </label>
              <select
                id="gender"
                name="gender"
                value={formData.gender}
                onChange={handleChange}
                required
                className="w-full px-3 py-2 bg-white border border-gray-300 rounded-lg text-gray-900 focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-green-500 text-sm md:text-base"
              >
                <option value="">Select Gender</option>
                <option value="male">Male</option>
                <option value="female">Female</option>
              </select>
            </div>

            {/* Phone Number */}
            <div>
              <label htmlFor="phone" className="block text-gray-700 font-medium mb-1 text-xs md:text-sm">
                Phone Number *
              </label>
              <input
                type="tel"
                id="phone"
                name="phone"
                value={formData.phone}
                onChange={handleChange}
                required
                className="w-full px-3 py-2 bg-white border border-gray-300 rounded-lg text-gray-900 focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-green-500 text-sm md:text-base"
              />
            </div>

            {/* Email Address (Optional) */}
            <div>
              <label htmlFor="email" className="block text-gray-700 font-medium mb-1 text-xs md:text-sm">
                Email Address (Optional)
              </label>
              <input
                type="email"
                id="email"
                name="email"
                value={formData.email}
                onChange={handleChange}
                className="w-full px-3 py-2 bg-white border border-gray-300 rounded-lg text-gray-900 focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-green-500 text-sm md:text-base"
              />
            </div>

            {/* KCSE Grade */}
            <div>
              <label htmlFor="kcseGrade" className="block text-gray-700 font-medium mb-1 text-xs md:text-sm">
                KCSE Grade *
              </label>
              <select
                id="kcseGrade"
                name="kcseGrade"
                value={formData.kcseGrade}
                onChange={handleChange}
                required
                className="w-full px-3 py-2 bg-white border border-gray-300 rounded-lg text-gray-900 focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-green-500 text-sm md:text-base"
              >
                <option value="">Select Grade</option>
                {kcseGrades.map(({ grade }) => (
                  <option key={grade} value={grade} className="text-gray-900">{grade}</option>
                ))}
              </select>
            </div>

            {/* Exam Body Selection */}
            <div>
              <label htmlFor="examBody" className="block text-gray-700 font-medium mb-1 text-xs md:text-sm">
                Exam Body *
              </label>
              <select
                id="examBody"
                name="examBody"
                value={formData.examBody}
                onChange={handleChange}
                required
                className="w-full px-3 py-2 bg-white border border-gray-300 rounded-lg text-gray-900 focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-green-500 text-sm md:text-base"
              >
                <option value="">Select Exam Body</option>
                <option value="internal" className="text-gray-900">Internal</option>
                <option value="JP" className="text-gray-900">JP International Examinations</option>
                <option value="CDACC" className="text-gray-900">CDACC Examination Body</option>
                <option value="KNEC" className="text-gray-900">KNEC</option>
              </select>
              <p className="mt-1 text-purple-300 text-xs">
                {formData.examBody === 'CDACC' 
                  ? 'CDACC uses 6-month semesters.' 
                  : formData.examBody ? 'Uses 3-month semesters.' : ''}
              </p>
            </div>

            {/* Course Selection */}
            <div>
              <label htmlFor="course" className="block text-gray-700 font-medium mb-1 text-xs md:text-sm">
                Course *
              </label>
              <select
                id="course"
                name="course"
                value={formData.course}
                onChange={handleChange}
                required
                disabled={loading || courses.length === 0}
                className="w-full px-3 py-2 bg-white border border-gray-300 rounded-lg text-gray-900 focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-green-500 text-sm md:text-base disabled:opacity-50 disabled:cursor-not-allowed"
              >
                <option value="">
                  {loading ? 'Loading courses...' : courses.length === 0 ? 'No courses available' : 'Select Course'}
                </option>
                {courses
                  .filter(course => {
                    if (!formData.examBody) return true;
                    // Use course.exam_body column first, fallback to ID prefix
                    const courseExamBody = course.exam_body || getExamBodyFromCourseId(course.id);
                    return courseExamBody === formData.examBody;
                  })
                  .map(course => (
                    <option key={course.id} value={course.id} className="text-gray-900">{course.name}</option>
                  ))}
              </select>
              {formData.examBody && courses.filter(course => {
                const courseExamBody = course.exam_body || getExamBodyFromCourseId(course.id);
                return courseExamBody === formData.examBody;
              }).length === 0 && (
                <p className="mt-2 text-red-300 text-sm">No courses available for this exam body.</p>
              )}
            </div>

            {/* Course Type (Auto-selected based on grade and exam body) */}
            {formData.course && formData.kcseGrade && formData.examBody && (
              <div>
                <label htmlFor="courseType" className="block text-gray-700 font-medium mb-1 text-xs md:text-sm">
                  Course Type *
                </label>
                <select
                  id="courseType"
                  name="courseType"
                  value={formData.courseType}
                  onChange={handleChange}
                  required
                  disabled={availableCourseTypes.length === 0}
                  className="w-full px-3 py-2 bg-white border border-gray-300 rounded-lg text-gray-900 focus:outline-none focus:ring-2 focus:ring-green-500 focus:border-green-500 text-sm md:text-base disabled:opacity-50 disabled:cursor-not-allowed"
                >
                  <option value="">
                    {availableCourseTypes.length === 0 ? 'No types available for your grade' : 'Select Type'}
                  </option>
                  {availableCourseTypes.map(type => (
                    <option key={type} value={type} className="text-gray-900">
                      {formatCourseTypeLabel(type, formData.examBody)}
                    </option>
                  ))}
                </select>
                {availableCourseTypes.length === 0 && (
                  <p className="mt-2 text-red-300 text-sm">Your grade doesn't meet the requirements for this course.</p>
                )}
              </div>
            )}

            {/* Suggested Courses */}
            {suggestedCourses.length > 0 && availableCourseTypes.length === 0 && (
              <div className="bg-yellow-500/20 border border-yellow-500/50 rounded-lg p-4">
                <p className="text-yellow-200 font-medium mb-2">Suggested courses for your grade:</p>
                <div className="space-y-2">
                  {suggestedCourses.slice(0, 5).map(course => (
                    <button
                      key={course.id}
                      type="button"
                      onClick={() => setFormData(prev => ({ ...prev, course: course.id }))}
                      className="w-full text-left px-3 py-2 bg-white/10 hover:bg-white/20 rounded text-purple-200 text-sm transition-colors"
                    >
                      {course.name}
                    </button>
                  ))}
                </div>
              </div>
            )}

            {/* Campus Radio Pills */}
            <div>
              <label className="block text-gray-700 font-medium mb-1 text-xs md:text-sm">Campus *</label>
              <div className="grid grid-cols-2 gap-1.5">
                {[{id: 'west', label: 'West Campus'}, {id: 'main', label: 'Main Campus'}].map(c => (
                  <button type="button" key={c.id} onClick={() => setFormData(p => ({...p, campus: c.id}))}
                    className={`p-3 rounded-lg border capitalize transition-all ${formData.campus === c.id ? 'border-green-500 bg-green-50 text-green-700' : 'border-gray-300 bg-white text-gray-500'}`}>
                    {c.label}
                  </button>
                ))}
              </div>
            </div>

            {/* Intake - loaded from backend academic_calendar */}
            <div>
              <label className="block text-gray-700 font-medium mb-1 text-xs md:text-sm">
                Intake *
              </label>
              {availableIntakes.length === 0 ? (
                <p className="text-gray-400 text-sm">Loading available intakes...</p>
              ) : (
                <div className="grid grid-cols-2 md:grid-cols-3 gap-1.5">
                  {availableIntakes.map(cal => {
                    const d = new Date(cal.term_start_date);
                    const monthName = d.toLocaleString('en-US', { month: 'long' });
                    const year = d.getFullYear();
                    const label = `${monthName} ${year}`;
                    return (
                      <button type="button" key={cal.id}
                        onClick={() => setFormData(p => ({...p, intake: label, academic_calendar_id: cal.id }))}
                        className={`p-3 rounded-lg border text-xs text-center transition-all ${formData.intake === label ? 'border-green-500 bg-green-50 text-green-700' : 'border-gray-300 bg-white text-gray-500'}`}>
                        {monthName} <br/> {year}
                      </button>
                    );
                  })}
                </div>
              )}
            </div>

            {/* Submit Button */}
            <button
              type="submit"
              disabled={submitting}
              className="w-full py-2 bg-green-600 hover:bg-green-700 text-white rounded-lg transition-colors duration-300 text-base font-semibold shadow-lg hover:shadow-xl disabled:opacity-50 disabled:cursor-not-allowed"
            >
              {submitting ? 'Submitting...' : 'Submit Application'}
            </button>
          </form>

          {/* Back to Home */}
          <div className="text-center mt-6">
            <Link
              href="/"
              className="inline-flex items-center gap-2 px-6 py-3 bg-white/10 hover:bg-white/20 border border-white/30 hover:border-white/50 text-white rounded-xl transition-all duration-300 text-sm md:text-base font-medium backdrop-blur-sm"
            >
              ← Back to Home
            </Link>
          </div>
        </div>
        )}

        {/* Step 2: Guardian Details */}
        {currentStep === 'guardian' && savedApplicationId && (
          <div className="bg-white rounded-xl p-4 md:p-5 border border-gray-200 shadow-sm">
            <div className="text-center mb-3">
              <div className="inline-block mb-4">
                <div className="relative w-16 h-16">
                  <Image
                    src="/logo.webp"
                    alt="East Africa Vision Institute Logo"
                    fill
                    className="object-contain"
                    sizes="96px"
                    loading="eager"
                  />
                </div>
              </div>
              <h1 className="text-lg md:text-xl font-bold text-white mb-1">Guardian Information</h1>
              <p className="text-gray-500 text-sm md:text-base">Please provide parent or guardian details</p>
            </div>

            <GuardianManager 
              applicationId={savedApplicationId} 
              onGuardianSaved={() => setCurrentStep('confirmation')}
            />
          </div>
        )}
      </div>
    </div>
  );
}
